### ISSUE TITLE
What is the LICENSE for this software? I don't see a LICENSE file. 

### ISSUE THREAD

**Issue by senrabc** [PopMedNet-Team/FDA-My-Studies-Mobile-Application-System#2]
Hi Guys. ,

The PopMedNet website has a reference to Apache 2.0 Licensing for open source software. Is this REPO licensed under Apache 2.0 Thanks - Chris Barnes

**Comment by micheas** [comment]
Similar concern.

the only license file I see is:
https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/blob/master/mobileAppStudy-hosting17.1/LICENSE.txt

> Copyright (c) 2017-2018 LabKey Corporation. All rights reserved. No portion of this work may be reproduced in any form or by
> any electronic or mechanical means without written permission from LabKey Corporation.

I'm concerned that this software is not opensource.

**Comment by hislop** [comment]
There's no top level license, and if you poke into the different folders, the files called "License.txt" contain different things!  In one folder, only a copyright; in another folder, a custom written text that seems intended to be a license; in a third folder, a reference to the MIT license.  People looking for an open source product won't be able to use this code base as it exists at the moment.  Cleaning up the files and making licensing clear would be much appreciated!

**Comment by kfogel** [comment]
+1 to the above comments.  Right now, this code is not open source software.

If one of your issues is that some of the code is in the public domain (because of the requirement that works produced by federal employees in the course of the work be public domain), and that therefore no open source license can be applied because no copyright license can be applied, that's usually solveable -- happy to discuss further.

But I don't think that's the issue, because there are plenty of license files in the tree right now.  Here's a review of the ones I was able to find in a quick scan:

* **`hphc_ios-master/HPHC/Pods/RealmSwift/LICENSE`** -- problematic b/c of REALM license portion; see also comments about export controls below

* **`hphc_ios-master/HPHC/Pods/IQKeyboardManagerSwift/LICENSE.md`** -- MIT (no problem)

* **`hphc_ios-master/HPHC/Pods/Realm/LICENSE`** -- problematic b/c of REALM license; see also comments about export controls below

* **`hphc_ios-master/HPHC/Pods/ActionSheetPicker-3.0/LICENSE`** -- MIT (no problem)

* **`hphc_ios-master/HPHC/Pods/SlideMenuControllerSwift/LICENSE`** -- MIT (no problem)

* **`hphc_ios-master/HPHC/Pods/SDWebImage/LICENSE`** -- MIT (no problem)

* **`hphc_ios-master/HPHC/Pods/CryptoSwift/LICENSE`** -- problematic because of non-standard license -- probably meant to be open source but not easily recognizeable as such

* **`fdahpStudyDesigner-master/fdahpStudyDesigner/src/main/webapp/vendor/tinymce/license.txt`** -- GNU LGPL (no problem)

* **`fdahpStudyDesigner-master/FDA HTML/vendor/tinymce/license.txt`** -- GNU LGPL (no problem)

* **`mobileAppStudy-hosting17.1/LICENSE.txt`** -- proprietary license, totally not open source

Regarding export controls:

A couple of the license files have this addendum at the end:

    EXPORT COMPLIANCE
    
    You understand that the Software may contain cryptographic
    functions that may be subject to export restrictions, and you
    represent and warrant that you are not (i) located in a
    jurisdiction that is subject to United States economic sanctions
    (“Prohibited Jurisdiction”), including Cuba, Iran, North Korea,
    Sudan, Syria or the Crimea region, (ii) a person listed on any
    U.S. government blacklist (to include the List of Specially
    Designated Nationals and Blocked Persons or the Consolidated
    Sanctions List administered by the U.S. Department of the
    Treasury’s Office of Foreign Assets Control, or the Denied Persons
    List or Entity List administered by the U.S. Department of
    Commerce) (“Sanctioned Person”), or (iii) controlled or 50% or
    more owned by a Sanctioned Person.
    
    You agree to comply with all export, re-export and import
    restrictions and regulations of the U.S. Department of Commerce or
    other agency or authority of the United States or other applicable
    countries. You also agree not to transfer, or authorize the
    transfer of, directly or indirectly, of the Software to any
    Prohibited Jurisdiction, or otherwise in violation of any such
    restrictions or regulations.

I don't see any reason why this belongs in the copyright license.  It's not a copyright law; it's an export control law, and it is in effect (in the U.S. at least) completely independently of the license.  If its inclusion in the license file is meant to suggest that the export controls are *also* being made a condition of redistribution as part of the copyright license, then that would render the entire license immediately non-open-source.

If your worry is that someone outside U.S. jurisdiction might ignore U.S. export control law, and that therefore the export control law has to be made part of the copyright license too, consider that that person is also outside the jurisdiction of U.S. copyright law -- and how likely is a foreign court to uphold a bizarre addendum to a copyright license that subjects someone in their jurisdiction to whatever arbitrary policies the U.S. Department of Commerce or other U.S. agencies come up with?  How would that court even determine what policies to consider: the ones in effect at the time the software license was applied, the ones in effect at the time the licensee received the code (and thus agreed to the copyright license), or the ones in effect at the time the violation is claimed?  It's a complete mess :-).  I urge you to take it out of the copyright license and simply rely on non-copyright-based export control law, which is how export control law is designed to work in the first place.

**Comment by PopMedNet-Team** [comment]
Thank you to everyone who brought this issue to our attention. We'll get your questions answered and get the issue resolved as soon as possible.

Thanks,
The FDA MyStudies team

**Comment by kfogel** [comment]
Thanks, @PopMedNet-Team.

**Comment by PopMedNet-Team** [comment]
No problem, you will likely see a response posted by @FDA-MyStudies

**Comment by FDA-MyStudies** [comment]
@hislop 

The text about an MIT license was included in error, that has been corrected to reflect the same license language as in the ios and android app folders.

**Comment by FDA-MyStudies** [comment]
We are currently working with our developers as well as the FDA to provide a top level license file that addresses the concerns raised in this issue. However, we can confirm that the intent of all parties involved in the development of this system, including FDA, is to provide an open source system that can be used without restriction.

**Comment by kfogel** [comment]
Thanks.  I see the `LICENSE.txt` file there now; have filed PR #18 with formatting fixes, so it's easier to recognize that it's the MIT license.
